

import Foundation

let PaymentTransactionDidCompleteNotification = "PaymentTransactionDidCompleteNotification"
let PaymentTransactionDidRestoreNotification = "PaymentTransactionDidRestoreNotification"
let PaymentTransactionDidFailNotification = "PaymentTransactionDidFailNotification"
let PaymentTransactionDidRestoreAllNotification = "PaymentTransactionDidRestoreAllNotification"

