

import Foundation
//import Haneke

struct TextureAtlasFileName {
  static let Environment = "Environment"
  static let Character = "Character"
  static let UserInterface = "UserInterface"
}

struct TextureFileName {
    static let StartLogo = "StartLogo"

    static let BackgroundStars = "BackgroundStars"
    static let BackgroundStars2 = "BackgroundStars2"
    static let BackgroundLargePlanets = "BackgroundLargePlanets"
    static let BackgroundSmallPlanets = "BackgroundSmallPlanets"
    static let PlanetGround = "PlanetGround"

    static let MuffyFlying = "MuffyFlying"
    static let MuffyStopFlying = "MuffyStopFlying"
    static let MuffyStanding = "MuffyStanding"
    static let MuffyDead = "MuffyDead"

    static let Shield = "Shield"
    static let ShieldBlur = "ShieldBlur"

    static let EngineFlame = "EngineFlame"
    
    static let CometLargeGlow = "CometLargeGlow"
    static let CometLarge = "CometLarge"
    static let CometLarge2 = "CometLarge2"
    static let CometLarge3 = "CometLarge3"
    static let CometLarge4 = "CometLarge4"
    static let CometLarge5 = "CometLarge5"
    static let CometLarge6 = "CometLarge6"
    static let CometLarge7 = "CometLarge7"
    static let CometLarge8 = "CometLarge8"
    static let CometLarge9 = "CometLarge9"
    static let CometLarge10 = "CometLarge10"
    static let CometLarge11 = "CometLarge11"
    static let CometLarge12 = "CometLarge12"
    static let CometLarge13 = "CometLarge13"
    static let CometLarge14 = "CometLarge14"
    static let CometLarge15 = "CometLarge15"
    static let CometLarge16 = "CometLarge16"
    static let CometLarge17 = "CometLarge17"
    static let CometLarge18 = "CometLarge18"
    static let CometLarge19 = "CometLarge19"
    static let CometLarge20 = "CometLarge20"
    static let CometLarge21 = "CometLarge21"
    static let CometLarge22 = "CometLarge22"
    static let CometLarge23 = "CometLarge23"
    
    static let CometMediumGlow = "CometMediumGlow"

    static let CometSmallGlow = "CometSmallGlow"
    
    static let CometStar = "CometStar"
    static let CometStarGlow = "CometStarGlow"
    static let CometStar2 = "CometStar2"
    static let CometStarGlow2 = "CometStarGlow2"
    static let CometStar3 = "CometStar3"
    static let CometStarGlow3 = "CometStarGlow3"

    static let ButtonAd = "BtnAd"
    static let ButtonLeaderboard = "BtnLeaderboard"
    static let ButtonMusic = "BtnMusic"
    static let ButtonMusicOff = "BtnMusicOff"
    static let ButtonSound = "BtnSound"
    static let ButtonSoundOff = "BtnSoundOff"
    static let ButtonPlay = "BtnPlay"
    static let ButtonPlayAgain = "BtnPlayAgain"
    static let ButtonHome = "BtnHome"
    static let ButtonResume = "BtnResume"
    static let ButtonEnemies = "BtnEnemies"
    static let LabelNewScore = "LabelNewScore"
    static let TapTip = "Hand"
    static let TapTip2 = "Hand"
    static let TapTip3 = "downHand"

    static let CrackedRed = "CrackedRed"
    static let CrackedSmall = "CrackedSmall"
    static let CrackedMedium = "CrackedMedium"
    static let CrackedLarge = "CrackedLarge"
    static let Explosion = "Explosion"
    
    static let kEnemiesButtonGO = "buttonfinishedGO"
    static let kBarackObama = "BarackObama"
    static let kBernieSanders = "BernieSanders"
    static let kFloRida = "FloRida"
    static let kHilaryClinton = "HilaryClinton"
    static let kJebBush = "JebBush"
    static let kMacMiller = "MacMiller"
    static let kMarcoRubio = "MarcoRubio"
    static let kTedCruz = "TedCruz"
    static let kVladimirPutin = "VladimirPutin"
    static let kNoImage = "officialquestion"
    static let kRosie = "Rosie"
    static let kMegyn = "Megyn"
    static let kBeckyG = "BeckyG"
    static let kSNL = "SNL"
    static let kHeidiCruz = "HeidiCruz"
    static let kJohnOliver = "JohnO"
    static let kNBC = "NBC"
    static let kJohnKasich = "JohnKasich"
    static let kMexico = "Mexico"
    static let kCloseEnemiesViewButton = "closeEnemiesViewButton"
}
